version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: event-postgres
    restart: always
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
